### ISSUE TITLE
导致电脑整体变卡顿？

### ISSUE THREAD

**Issue by BaiFeng666** [Oxygen1a1/InfinityHook_latest#2]
今天下午忽然感觉整个电脑非常卡 例如平时打开任务管理器只需要0.5秒 现在需要1秒以上 并且拖动窗口什么的操作都很卡顿掉帧
看了任务管理器也没发现什么占CPU和内存的软件
于是排查了半天，发现是InfinityHook_lastest导致的
哪怕不Hook任何函数 仅Init初始化InfinityHook_lastest就会让电脑整个变卡 
注释了Hook的Init就不卡了 于是得出这样的结论
（朋友的电脑也测试了，也会出现这样的大幅度性能下降的问题）
希望大佬能优化一下这个问题，项目非常好用

**Comment by BaiFeng666** [comment]
感觉是在'stack_trace_to_syscall()'遍历堆栈导致的性能损耗

**Comment by Oxygen1a1** [comment]
这个是inf hook的通病，要遍历堆栈，我测试了下，虽然卡，但是不至于卡的厉害，性能下降20-30%应该是正常的，虚拟机会很卡

**Comment by Oxygen1a1** [comment]
infhok通病
